### ISSUE TITLE
Consider portable local cluster

### ISSUE THREAD

**Issue by dankohn** [cncf/demo#170]
@zilman @leecalcote We were joking about you having a cluster that could fit in your backpack, but this one would probably speed up your debug cycles versus the latency of working with the cloud.

https://hackernoon.com/diy-kubernetes-cluster-with-x86-stick-pcs-b0b6b879f8a7
https://news.ycombinator.com/item?id=12985525

I will fund this as one of your deployment targets if you're interested.

**Comment by namliz** [comment]
@dankohn this is neat and I'm interested just for playfulness of it to be honest, but it doesn't really speed things up. 

`cncfdemo bootstrap aws cluster` runs in 5-6 minutes, what I'm really lacking is a bit of infrastructure to have more than one cluster (version) going at a time. But that's coming soon.

**Comment by dankohn** [comment]
I'll close the issue but a reminder that it would make for a pretty cool live demo, and doesn't rely on conference Wi-Fi!

**Comment by namliz** [comment]
That's also true, and it would be a lot of fun. This is a fine idea. Lets grab some for next con. I have reason to come by NYC around January so I can pick them up. 

I'll research a nice safe model. If somebody is reading this and knows compute sticks chime in. :)
