### ISSUE TITLE
boinc client needs mice device

### ISSUE THREAD

**Issue by namliz** [cncf/demo#19]
https://setiathome.berkeley.edu/forum_thread.php?id=79537

/dev/input/mice is being used by boinc for entropy or something -- assuming X by boinc maintainers.. is a problem.

**Comment by leecalcote** [comment]
Could be a short call with IBM today...

**Comment by namliz** [comment]
It's taking tasks successfully and doing.. something. But there's not
enough feedback if it's completing tasks or the bug ruins it. Results get
delayed 24 hours.

The worst case scenario is having to pull in all of X as a dependency which
is terrible, but that would work around it.

**Comment by namliz** [comment]
Confirmed as warning and not a show stopper, closing.
