### ISSUE TITLE
Phabricator on Cloud Native Landscape Project poster

### ISSUE THREAD

**Issue by stevexyz** [cncf/demo#200]
I was having a look on the Cloud Native Landscape Project poster and I noticed that Phabricator (an extremely good cloud code manager) is not even mentioned.

Is coming from Facebook, but now is open sourced and used by many, famous and less famous development teams (e.g. Wikimedia Foundation, Blender, FreeBSD, Twitter, etc. etc.).

Have a look on it if you don't know, I think it's worthwhile.

Best Regards
_Stefano

**Comment by namliz** [comment]
@stevexyz Are you saying you think it is worthwhile to include on the poster? Possibly so, but this is the repo for something else.

You can suggest feedback about the poster to @dankohn.

**Comment by dankohn** [comment]
Apologies. @stevexyz can you please open an issue on https://github.com/cncf/landscape
