### ISSUE TITLE
Adjust language about CNCF Community cluster in overview

### ISSUE THREAD

**Issue by jacobsmith928** [cncf/demo#225]
Currently the text reads as follows, which is outdated and could be replaced with text from the /cluster repo https://github.com/cncf/cluster

CNCF Community Cluster

Donated by Intel, a 1,000 node cluster of servers is running in Switch, Las Vegas, to be used by the CNCF community. Visit these links for a description of the cluster project page or to be involved in the cluster community.

**Comment by dankohn** [comment]
Fixed, thanks.
