### ISSUE TITLE
CLA bot needs to show in progress status

### ISSUE THREAD

**Issue by dankohn** [cncf/demo#8]
@caniszczyk I watched the [PR](https://github.com/cncf/demo/pull/7) that @bgrant0607 just submitted, and I'm concerned that the CLAbot is not quite configured correctly.

The issue is that when creating the pull request, the status API should show in progress from the CLAbot, to let the submitter know that it's running. Then, it should change to passed or failed.

Right now, it seems to show as green and then come back as pass or fail a minute later.

**Comment by thelinuxfoundation** [comment]
The CLA check should show up immediately (GitHub knows it's a required status check), but grey (pending/waiting or some such) and then come back as green or red once the status API is sent from us.  If it's not, then Github must have changed something.  Can you send a screenshot of what it looks like when the pull request first happens?
